version: '3.6'
services:
  jenkins:
    image: jenkins/jenkins:lts
    environment:
      JAVA_OPTS: -Djenkins.install.runSetupWizard=false
      JENKINS_OPTS: --argumentsRealm.roles.user=admin --argumentsRealm.passwd.admin=admin --argumentsRealm.roles.admin=admin
    container_name: 'jenkins'
    ports:
      - 8080:8080
    volumes:
      - ./jenkins/plugins.txt:/usr/share/jenkins/ref/plugins.txt
      - ./jenkins/jenkinsfile:/var/jenkins_home/workspace/Jenkinsfile
      - ./jenkins/initial.sh:/usr/share/jenkins/ref/initial.sh
    command: >
        bash -c "jenkins-plugin-cli -f /usr/share/jenkins/ref/plugins.txt
        && ./usr/local/bin/jenkins.sh" & /usr/share/jenkins/ref/initial.sh
    networks: 
      - tp_network
networks:
  tp_network:
    name: tp_network
