version: '3.6'
services:
  jenkins:
    image: 'jenkins/jenkins:latest'
    environment:
      JAVA_OPTS: -Djenkins.install.runSetupWizard=false
      JENKINS_OPTS: --argumentsRealm.roles.user=admin --argumentsRealm.passwd.admin=admin --argumentsRealm.roles.admin=admin
    container_name: 'jenkins'
    ports:
      - 8080:8080
    volumes:
      - './DATA/jenkins:/var/jenkins_home'
    networks: 
      - tp_network
networks:
  tp_network:
    name: tp_network
